name: NCOMPLETE
description: Thinking on Design, Being & Incompleteness - AKA -
  forgetting to stop asking questions halfway through answering them.

# avatar: add later
markdown: kramdown
permalink: n-complete/:categories/:year/:month/:day/:title

footer-links:
  twitter: nuanc3
